name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: actions-runner-scale-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
